ARTICLE_TYPES:
  homepage:
    title: Startseite
    template: startseite
  default:
    title: Standardseite
    template: standard
  varilog:
    title: Varilog
    template: varilog
  varisale:
    title: Varisale
    template: varisale
  varisale.checkout:
    title: Varisale Warenkorb
    template: varisale.checkout