# Kopiere mich nach develop/config!

varisale:
   # Hier findet die allgemeine Konfiguration von varisale statt.

   config:
      # Die untenstehenden Angaben bestimmen, in welchen Attributen varisale
      # nach essenziellen Informationen in Produkten bzw. Benutzer-Accounts
      # suchen wird.

      attributes:
         price: price
         taxrate: taxrate
         users:
            billing_country: country
            delivery_country: country
            # '__login__' ist ein besonderer Wert, der auf kein echtes Attribut,
            # sondern den Login deines Benutzers zeigt.
            email: __login__

      # Die folgenden Optionen steuern das Erscheinungsbild des Backends und
      # ermöglichen es, ohne Anpassungen der Templates bestimmte Features zu
      # verstecken.

      backend:
         # Wenn true, werden variable Attribute angezeigt (auch wenn man sie nicht
         # bearbeiten kann), ansonsten erscheinen sie gar nicht im Produkt-Formular.
         show_variable_attributes: false

         # Wie viele Bestellungen sollen pro Seite angezeigt werden?
         orders_per_page: 25

         # Schaltet den Sanity-Check aus, der im Backend, wenn der Developer Modus
         # aktiviert ist, die Konfiguration auf mögliche Probleme untersucht.
         sanity_check: true

         # Schaltet das Feature, Verknüpfungen von Produkten zu erstellen, ab.
         product_links: false

         # Schaltet das Feature, Varianten von Produkten zu erstellen, ab.
         product_variants: false

         # Schaltet die Möglichkeit, den Produktstatus zu ändern, ab. Nützlich,
         # wenn im Frontend eh immer alle Produkte angezeigt werden. Produkte
         # werden jedoch immer noch in der Datenbank als 'offline' erzeugt, nur
         # nicht mehr so im Backend angezeigt.
         product_status: true

         # Dito für Kategorien
         category_status: true

         # Schaltet die Möglichkeit, die Kategorie-Struktur zu bearbeiten, ab.
         category_editing: true

      # In diesem Verzeichnis (relativ zum Root des Projekts) liegen projektspezifische
      # Templates. So kann die Startseite in TEMPLATE_DIRECTORY/templates/index.phtml
      # überschrieben werden.
      template_directory: develop/varisale

      # Steuerkonfiguration
      taxes:
         # Diese beiden Optionen steuern, ob die Lieferkosten und/oder die
         # Rechnungskosten steuerlich behandelt werden sollen. Wenn true, werden
         # sie entsprechend ihrer Konfiguration mit Steuern versehen.
         delivery: false
         billing: true

   # Produkttypen steuern, welche Attribute für welches Produkt verfügbar sind
   # und bestehen jeweils aus einem internen Namen (Key) sowie dazu einem Titel
   # und einem Icon.
   # Wird nur ein Typ definiert, erscheint im Backend beim Anlegen eines Produkts
   # keine Auswahl dafür.

   producttypes:
      default:                       # kann nicht gelöscht oder umbenannt werden!
         title: Standardprodukt      # der Titel darf jedoch frei gewählt werden
         icon: ruby.png              # verfügbare Icons liegen in varisale/assets/images/products

   # Die Attribute sind das Herz von varisale und bestimmen die Eigenschaften
   # der Produkte. Siehe die Dokumentation von varisale unter www.varisale.de
   # für Infos, was hier wie definiert werden muss.
   # Ein Preis- und ein Steuersatz-Attribut müssen *immer* vorhanden sein!

   attributes:
      price:
         title: Preis
         datatype: varisale.money
         params:
            taxes: 0
            currency: EUR
            fixed: true       # verhindern, dass man die Währung pro Produkt auswählen kann
         default: '0.00EUR'
         producttypes: [default]
      taxrate:
         title: Steuersatz
         datatype: select
         params:
            source: query
            query: 'SELECT id,title FROM %%PREFIX%%wv13_taxrates WHERE 1 ORDER BY title'
            style: select
            min: 1
            max: 1
         default: 1
         producttypes: [default]
      image:
         title: Bild
         datatype: media
         producttypes: [default]
      description:
         title: Beschreibung
         datatype: stringtext
         producttypes: [default]
      delivery_time:
         title: Lieferzeit
         datatype: stringline
         producttypes: [default]
      weight:
         title: Gewicht
         datatype: stringline
         producttypes: [default]
