# Kopiere mich nach develop/config!

# Hier wird konfiguriert, in welchen Metainfos die Kerninformationen der
# Artikel kodiert sind. Falls die Inhalte in der mitglieferten metainfos.yml
# (bzw. ihrer Kopie in develop/config) angepasst wurden, müssen diese Änderungen
# auch hier nachgetragen werden.

varilog:
  articletypes: [varilog]
  metainfos:
    created: varilog_createdate
    tags: varilog_tags
    categories: varilog_categories
    trackbacks: varilog_trackbacks
    comments: varilog_allow_comments
