title: Default Page

tabs:
  content:
    label: Inhalt
    icon: page
    columns:
      - width: 2/3
        sections:
          content:
            type: fields
            fields:
              text:
                label: Text
                type: textarea
                size: large
      - width: 1/3
        sections:
          gallery:
            extends: sections/images
            headline: Gallery
            template: image
  seo:
    label: SEO
    icon: search
    sections:
      seo:
        type: fields
        fields:
          metaTitle:
            label: Meta-Titel
            type: text
            required: true
          metaDescription:
            label: Meta-Beschreibung
            type: textarea
            buttons: false    