title: toettchen.de

tabs:
  content:
    label: Seiten
    icon: page
    sections:
      pages:
        type: pages
  footer:
    label: Footer
    icon: globe
    fields:
      links:
        type: pages