<p><strong>Liefermethode:</strong> <?php
	$methods  = Varisale::getDeliveryMethods();
	$links    = array();
	$selected = $cart->getDeliveryMethod();

	if (!$selected) {
		$links[] = '<a href="/kaufen/warenkorb/index.php?action=delivery&amp;id=0"><strong>keine</strong></a>';
	}
	else {
		$links[] = '<a href="/kaufen/warenkorb/index.php?action=delivery&amp;id=0">keine</a>';
	}

	foreach ($methods as $method) {
		$id = $method->getID();

		if ($selected && $id == $selected->getID()) {
			$links[] = '<a href="/kaufen/warenkorb/index.php?action=delivery&amp;id='.$id.'"><strong>'.sly_html($method->getTitle()).'</strong></a>';
		}
		else {
			$links[] = '<a href="/kaufen/warenkorb/index.php?action=delivery&amp;id='.$id.'">'.sly_html($method->getTitle()).'</a>';
		}
	}

	print implode(' | ', $links);
?> <?php if (Varisale::getCurrentUser()): ?><strong>geliefert an die folgende Adresse: </strong> <?php
	$links    = array();
	$selected = $cart->getDeliveryAddress();

	if ($selected === false) {
		$links[] = '<a href="/kaufen/warenkorb/index.php?action=deliveryaddress&amp;set_id=0"><strong>keine</strong></a>';
	}
	else {
		$links[] = '<a href="/kaufen/warenkorb/index.php?action=deliveryaddress&amp;set_id=0">keine</a>';
	}

	foreach ($_SETS as $set => $name) {
		if ($selected == $set) {
			$links[] = '<a href="/kaufen/warenkorb/index.php?action=deliveryaddress&amp;set_id='.$set.'"><strong>'.sly_html($name).'</strong></a>';
		}
		else {
			$links[] = '<a href="/kaufen/warenkorb/index.php?action=deliveryaddress&amp;set_id='.$set.'">'.sly_html($name).'</a>';
		}
	}

	print implode(' | ', $links);
?><?php endif; ?></p>
