<tbody><?php foreach ($cart->getItems() as $item): ?><tr class="item summary">
	<td class="id"><?php print $item->getID() ?></td>
	<td class="title"><?php print sly_html($item->getProduct()->getTitle()) ?></td>
	<td class="quantity"><input type="text" class="quantity" name="quantity_<?php print $item->getID() ?>" value="<?php print $item->getQuantity() ?>" /></td>
	<td class="netto"><?php print sly_html($item->getProduct()->getNettoPrice()) ?></td>
	<td class="brutto"><?php print sly_html($item->getProduct()->getBruttoPrice()) ?></td>
	<td class="taxrate"><?php print sly_html($item->getTaxRate()->getTitle()) ?></td>
	<td class="totalbrutto"><?php print sly_html($item->getBruttoPrice()) ?></td>
	<td class="remove"><a href="/kaufen/warenkorb/?action=remove&amp;ident=<?php print $item->getID() ?>">entfernen</a></td>
</tr><?php foreach ($item->getValues() as $attrName => $value): ?><tr class="item values fixed">
	<td>&nbsp;</td>
	<td class="title" colspan="3"><em><?php print sly_html($attrName) ?>:</em></td>
	<td class="input" colspan="4"><?php print sly_html(is_array($value) ? sly_Util_String::humanImplode(array_values($value)) : $value) ?></td>
</tr><?php endforeach; foreach ($item->getUserValues() as $attrName => $value): ?><tr class="item values variable">
	<td>&nbsp;</td>
	<td class="title" colspan="3"><em><?php print sly_html($attrName) ?>:</em></td>
	<td class="input" colspan="4">
		<input type="text" class="text" name="value_<?php print $item->getID() ?>_<?php print $attrName ?>" value="<?php print sly_html(is_array($value) ? sly_Util_String::humanImplode(array_values($value)) : $value) ?>" />
	</td>
</tr>	<?php endforeach; endforeach ?></tbody>
