<?php
if ($setID != -1) {
	$user->setSetID($setID);
}
?>

<h3><?php print $setID == -1 ? 'Neues Profil anlegen' : 'Mein Profil' ?></h3>

<form method="post" action="/kaufen/warenkorb/index.php?action=<?php print $setID == -1 ? 'createset' : 'updateuser' ?>">
	<?php foreach ($user->getValues() as $attr => $value): ?>
	<div class="row">
		<label><?php print sly_html($attr) ?></label>
		<?php if ($attr === 'country'): ?>
			<select name="attribute_country" size="1">
				<?php foreach (Varisale::getCountries() as $country): ?>
				<option value="<?php print $country->getID() ?>"<?php print $setID != -1 && $country->getID() == key($value) ? ' selected="selected"' : '' ?>><?php print sly_html($country->getFullName()) ?></option>
				<?php endforeach ?>
			</select>
		<?php else: ?>
			<input type="text" class="text" name="attribute_<?php print $attr ?>" value="<?php print $setID == -1 ? '' : $value ?>" />
		<?php endif ?>
	</div>
	<?php endforeach ?>
	<div class="row">
		<input type="hidden" value="<?php print $setID ?>" name="set_id" />
		<input type="submit" value="<?php print $setID == -1 ? 'Neues Profil speichern' : 'Profil aktualisieren' ?>" class="submit" />
		<?php if ($setID != -1 && count($user->getSetIDs()) > 1): ?>
		<input type="submit" value="Profil löschen" name="deleteset" />
		<?php endif ?>
	</div>
</form>
